version: 2.1

orbs:
  gh-release: vertexproject/github-release@0

commands:

  do_report_coverage:
    description: "Codecov report upload"
    steps:
      - run:
          name: Upload Coverage Results
          command: |
            # Download and verify the codecov binary
            curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import # One-time step
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
            gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
            shasum -a 256 -c codecov.SHA256SUM
            chmod +x codecov
            # Activate our venv and generate a xml report
            . venv/bin/activate
            python -m coverage xml
            # Execute the binary...
            ./codecov \
              -t "${CODECOV_TOKEN}" \
              -n "${CODECOV_PREFIX}${PYVERS}node${CIRCLE_NODE_INDEX}" \
              -F python \
              -f ./coverage.xml \
              -v \
              -Z || echo 'Codecov upload failed'
            gcovr --xml gcoverage.xml
            ./codecov \
              -t "${CODECOV_TOKEN}" \
              -n "${CODECOV_PREFIX}${PYVERS}node${CIRCLE_NODE_INDEX}" \
              -F c-ext \
              -f ./gcoverage.xml \
              -v \
              -Z || echo 'Codecov upload failed'

  do_venv_setup:
    description: "Setup venv for testing"
    steps:
      - run:
          name: setup venv
          command: |
            python3 -m venv --copies venv
            . venv/bin/activate
            python3 -m pip install -U wheel pip setuptools gcovr pytest

      - run:
          name: install yyjson
          command: |
            . venv/bin/activate
            CFLAGS="--coverage -g -O0" python3 -m pip install -U --upgrade-strategy=eager -e .

  do_test_execution:
    description: "Execute unit tests via pytest"
    steps:
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            GCOV_PREFIX=test-reports GCOV_PREFIX_STRIP=8 python3 -m pytest \
              -v -rs \
              --durations 6 \
              -p no:logging \
              --junitxml=test-reports/junit.xml \
              -o junit_family=xunit1 \
              ${COVERAGE_ARGS}

  test_steps_python:
    description: "Python test steps"
    steps:
      - checkout

      - run:
          name: python version dump
          command: |
            python -c "import sys; print(sys.version)" | tee -a /tmp/python.version

      - restore_cache:
          keys:
            - v5-venv-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "pyproject.toml" }}-{{ checksum "/tmp/python.version" }}

      - do_venv_setup

      - save_cache:
          paths:
            - ./venv
          key: v5-venv-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "pyproject.toml" }}-{{ checksum "/tmp/python.version" }}

      - do_test_execution

      - do_report_coverage

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  deploy_pypi_prologue:
    description: "Common Pypi prologue"
    steps:
      - checkout

      - run:
          name: python version dump
          command: |
            python -c "import sys; print(sys.version)" | tee -a /tmp/python.version

      - restore_cache:
          keys:
            - v5-venv-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "pyproject.toml" }}-{{ checksum "/tmp/python.version" }}

      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -U wheel pip setuptools twine build
            python3 -m pip install -U -r requirements_dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v5-venv-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "pyproject.toml" }}-{{ checksum "/tmp/python.version" }}

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: set commit
          command: |
            . venv/bin/activate
            python ./scripts/replace_commit.py

  deploy_pypi_tag_verify:
    description: "Verify the git tag"
    steps:
      - run:
          name: verify git tag vs. version
          command: |
            . venv/bin/activate
            python ./scripts/verify_version.py

  deploy_pypi_sdist_build:
    description: "Build sdist packages for pypi"
    steps:
      - run:
          name: create packages
          command: |
            . venv/bin/activate
            python -m build --sdist

      - run:
          name: smoke packages
          command: |
            mkdir -p /tmp/sdisttest
            python3 -m venv /tmp/sdisttest/venv
            cp dist/*.tar.gz /tmp/sdisttest
            cd /tmp/sdisttest
            . ./venv/bin/activate
            python3 -m pip install -U pip twine setuptools
            python3 -m twine check *.tar.gz
            python3 -m pip install *.tar.gz
            python3 -c "$PYPI_SMOKE_CODE"
            deactivate

  deploy_pypi_wheel_build:
    description: "Build wheel packages for pypi"
    steps:
      - run:
          name: create packages
          command: |
            . venv/bin/activate
            export DIST_EXTRA_CONFIG=/tmp/build-opts.cfg
            echo -e "[bdist_wheel]\npython_tag=$PYTHON_TAG" > $DIST_EXTRA_CONFIG
            python -m build --wheel

      - run:
          name: smoke packages
          command: |
            mkdir -p /tmp/wheeltest
            python3 -m venv /tmp/wheeltest/venv
            cp dist/*.whl /tmp/wheeltest
            cd /tmp/wheeltest
            . ./venv/bin/activate
            python3 -m pip install -U wheel pip twine setuptools
            python3 -m twine check *.whl
            python3 -m pip install *.whl
            python3 -c "$PYPI_SMOKE_CODE"
            deactivate

  deploy_pypi_upload:
    description: "Upload packages to pypi"
    steps:
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

jobs:

  python311:
    resource_class: xlarge
    docker:
      - image: cimg/python:3.11
        environment:
          PYVERS: 3.11
          RUN_SYNTAX: 1
          COVERAGE_FILE: test-reports/<< pipeline.git.revision >>/.coverage
          COVERAGE_ARGS: --cov yyjson --cov-append

    working_directory: ~/repo

    steps:
      - test_steps_python

  deploy_pypi:
    docker:
      - image: cimg/python:3.11
        environment:
          PYPI_SMOKE_CODE: import yyjson; print(yyjson.__package__)
          PYTHON_TAG: py311

    steps:
      - deploy_pypi_prologue
      - deploy_pypi_tag_verify
      - deploy_pypi_wheel_build
      - deploy_pypi_sdist_build
      - deploy_pypi_upload

workflows:
  version: 2.1
  run_tests:
    unless:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - python311:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - deploy_pypi:
          requires:
            - python311
          context:
            - PublicPypiAccess
          filters:
            tags:
              only: /^v2\.[0-9]+\.[0-9]+((a|b|rc)[0-9]*)?$/
            branches:
              ignore: /.*/

      - gh-release/dorelease:
          requires:
            - python311
          context:
            - GithubMachine
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+((a|b|rc)[0-9]*)?$/
            branches:
              ignore: /.*/
